version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:9.1    
    working-directory: ~/my-app 
    steps:
      - run: echo This is the build step

  test:
    docker:
      - image: circleci/node:9.1    
    working-directory: ~/my-app
    steps:
      - run: echo This is the test step   

  deploy:
    docker:
      - image: circleci/node:9.1
    working-directory: ~/repo
    steps:
      - run: echo This is the deploy step
      
workflows:
  version: 2.1
  jobs:
    build:
    test:
      requires:
        - build
    deploy:
      requires:
        - test    
